version: 2.0

jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout

      - run: docker-compose build

      - run: docker-compose up -d

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
